### ISSUE TITLE
Dev server getting started guide

### ISSUE THREAD

**Issue by akats** [BIDMCDigitalPsychiatry/LAMP-server#1]
It would be nice to have a getting started guide for creating your own dev server.  I had one confirmed issue and one that I didn't investigate thoroughly enough:
1. (confirmed) How do I fill the auth section of the secrets file and create an initial user
2.  I built MSSQL, ran it with `-p 1434:1434 -p 1433:1433`, made sure the ports are exposed when I run nmap localhost, but when I ran the server, I got:
`(node:1) UnhandledPromiseRejectionWarning: ConnectionError: Failed to connect to 127.0.0.1:1433 - connect ECONNREFUSED 127.0.0.1:1433`

Here is my secrets file:
```
export default {
auth: {
hipaa: '',
oauth: '',
root: ''
},
sql: {
user: 'TEST',
   password: 'TEST12345',
   server: '127.0.0.1',
   port: 1433,
   database: 'LAMP'
}
}
```

**Comment by nerfanian** [comment]
Hi @avaidyam 
I'm running into similar issues as above, just wondering if there's a getting started guide yet?

**Comment by avaidyam** [comment]
Hey all - we are slowly rebuilding our documentation at https://docs.lamp.digital/ and though I'm still fleshing things out and making it easier to use, if you tap on the "Developer" role in that page you'll be able to find the deployment instructions. [Here's a direct link for now.](https://www.notion.so/digitalpsychiatry/Cloud-Deployment-Infrastructure-ebf62b0a24614d0c9b22a5817fe3e803) (There's a lot still in progress but this should help you get started now!)
